services:
  pokemon_db:
    image: postgres:15-alpine
    container_name: pokemon_prod_db
    restart: always
    env_file:
      - .env
    volumes:
      - pokemon_data:/var/lib/postgresql/data
    networks:
      - pokemon_network

  pokemon_api:
    build: .
    container_name: pokemon_prod_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - pokemon_db
    networks:
      - pokemon_network

networks:
  pokemon_network:
    driver: bridge

volumes:
  pokemon_data:
